development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  # Using async for production as a placeholder. Change this to `postgresql` or `redis` when setting up Cable for production.

