default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  # database: cache
  <<: *default

# development:
#   store: memory_store

# test:
#   store: null_store

# production:
#   store: memory_store
#   # Uncomment the database line when you set up caching in production:
#   database: pest_control_scheduling_production_cache

# development:
#   adapter: memory_store

# test:
#   adapter: null_store

# production:
#   adapter: memory_store
#   # Uncomment and configure the database option when ready to use SolidCache:
#   # adapter: solid_cache
#   # database: pest_control_scheduling_production_cache
