default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pest_control_scheduling_development

test:
  <<: *default
  database: pest_control_scheduling_test

production:
  <<: *default
  database: pset_s_db
  username: pset_s_db_user
  password: HHxwNNvbaI9C2NnNhuW9R3sQgk2PeItG
  host: localhost
  port: 5432
  verbose: true

  cable:
    <<: *default
    database: pset_s_db
    username: pset_s_db_user
    password: HHxwNNvbaI9C2NnNhuW9R3sQgk2PeItG
    host: localhost
    port: 5432
