default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pest_control_scheduling_development

test:
  <<: *default
  database: pest_control_scheduling_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  username: <%= Rails.application.credentials.database_username %>
  password: <%= Rails.application.credentials.database_password %>

  # Uncomment this if you're using a separate database for Action Cable
  # cable:
  #   <<: *default
  #   database: pest_control_scheduling_production_cable
